import { chromium } from 'playwright';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import http from 'node:http';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash, randomBytes } from 'node:crypto';
import { createBridge } from '../src/server.js';
import { ROOT } from '../src/config.js';
import { TOOLS } from '../src/tools.js';

const out = join(ROOT, 'output', 'playwright'); mkdirSync(out, { recursive: true });
const checks = [];
const mark = name => { checks.push(name); console.log(`PASS ${name}`); };
const uploadRoot = mkdtempSync(join(tmpdir(), 'aib-upload-test-'));
const uploadPath = join(uploadRoot, 'fixture.zip');
const uploadBytes = Buffer.from('fixture upload bytes');
writeFileSync(uploadPath, uploadBytes);
const uploadSha = createHash('sha256').update(uploadBytes).digest('hex');
const config = { port: 0, agentToken: randomBytes(32).toString('hex'), extensionToken: randomBytes(32).toString('hex'), uploadRoots: [uploadRoot] };
let mockMode = 'task', modelRequests = 0;
const mockModel = http.createServer(async (req, res) => {
  let raw = ''; for await (const chunk of req) raw += chunk;
  const body = JSON.parse(raw); modelRequests++;
  if (mockMode === 'slow') { setTimeout(() => { if (!res.destroyed) res.end(JSON.stringify({ choices: [{ message: { content: 'late reply' } }] })); }, 2000); return; }
  const content = body.messages.at(-1).content[0].text;
  const observation = JSON.parse(content.slice(content.indexOf('{')));
  const acted = body.messages.filter(m => m.role === 'tool').length;
  const name = acted === 0 ? 'browser_fill' : 'browser_key';
  const inputRef = observation.elements.find(e => e.label === '消息草稿').ref;
  const args = acted === 0 ? { tabId: observation.testTabId, ref: inputRef, text: '来自模拟模型的任务' } : { tabId: observation.testTabId, ref: inputRef, key: 'Enter' };
  // Bind to the tab ID supplied by the runner's system message, never a guessed tab.
  args.tabId = Number(/browser tab (\d+)/.exec(body.messages[0].content)[1]);
  const message = acted >= 2 ? { role: 'assistant', content: '本地模拟模型任务完成；浏览器动作已实际执行。' } : { role: 'assistant', tool_calls: [{ id: `mock-${acted}`, type: 'function', function: { name, arguments: JSON.stringify(args) } }] };
  res.setHeader('Content-Type', 'application/json'); res.end(JSON.stringify({ choices: [{ message }] }));
});
await new Promise(resolve => mockModel.listen(0, '127.0.0.1', resolve));
const bridge = createBridge(config, { modelLoader: () => ({ baseUrl: `http://127.0.0.1:${mockModel.address().port}/v1`, model: 'explicit-simulated-test-model', mode: 'tools' }) }); const address = await bridge.listen(); config.port = address.port;
const fixture = http.createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
  res.end(`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>本地浏览器验收</title><style>body{font:18px sans-serif;padding:50px;background:#f0f7f4;color:#19382b}input,button{font:inherit;padding:12px}#hidden,#upload,#options{display:none}#options.open{display:block}</style><h1>本地浏览器验收</h1><p>此页是测试夹具，没有外部服务。</p><label for="draft">消息草稿</label><input id="draft"><button id="send">发送到本地测试页</button><label for="task">赛题选择</label><input id="task" role="combobox" readonly aria-expanded="false"><div id="options" role="listbox"><div role="option">Task 108 topk_sigmoid</div><div role="option">Task 109 zero_experts_identity</div></div><label for="upload">ZIP 上传</label><input id="upload" type="file" accept=".zip"><p id="reply">等待输入</p><input type="password" value="PASSWORD_SECRET"><p id="hidden">HIDDEN_SECRET</p><p data-ai-private>PRIVATE_SECRET</p><button id="replace">替换按钮</button><a href="https://not-allowed.example/">未授权链接</a><div style="height:1400px"></div><script>document.querySelector('#send').onclick=()=>{document.querySelector('#reply').textContent='本地回显：'+document.querySelector('#draft').value};document.querySelector('#upload').onchange=e=>{document.querySelector('#reply').textContent='已选择：'+e.target.files[0].name+':'+e.target.files[0].size};const task=document.querySelector('#task'),options=document.querySelector('#options');task.onclick=()=>{options.classList.add('open');task.setAttribute('aria-expanded','true')};options.onclick=e=>{if(e.target.getAttribute('role')==='option'){task.value=e.target.textContent;options.classList.remove('open');task.setAttribute('aria-expanded','false');task.dispatchEvent(new Event('change',{bubbles:true}))}};</script></html>`);
});
await new Promise(resolve => fixture.listen(0, '127.0.0.1', resolve));
const origin = `http://127.0.0.1:${fixture.address().port}`;
const otherFixture = http.createServer(fixture.listeners('request')[0]);
await new Promise(resolve => otherFixture.listen(0, '127.0.0.1', resolve));
const otherOrigin = `http://127.0.0.1:${otherFixture.address().port}`;
const profile = mkdtempSync(join(tmpdir(), 'aib-browser-test-'));
const tempState = mkdtempSync(join(tmpdir(), 'aib-state-test-'));
writeFileSync(join(tempState, 'config.json'), JSON.stringify(config));
const bundled = join(process.env.LOCALAPPDATA || '', 'ms-playwright', 'chromium-1228', 'chrome-win64', 'chrome.exe');
const executablePath = process.env.AIB_TEST_CHROMIUM || (existsSync(bundled) ? bundled : undefined);
let context, client;
try {
  const extensionPath = join(ROOT, 'extension');
  context = await chromium.launchPersistentContext(profile, { executablePath, channel: 'chromium', headless: true, viewport: { width: 1200, height: 900 }, args: [`--disable-extensions-except=${extensionPath}`, `--load-extension=${extensionPath}`] });
  let worker = context.serviceWorkers()[0];
  if (!worker) worker = await context.waitForEvent('serviceworker');
  const extensionId = new URL(worker.url()).host;
  worker.on('console', msg => { if (msg.type() === 'error') console.error('WORKER:', msg.text()); });
  const panel = await context.newPage(); await panel.goto(`chrome-extension://${extensionId}/panel.html`);
  panel.on('pageerror', error => console.error('PANEL ERROR:', error.message));
  await panel.locator('#token').fill(config.extensionToken);
  await panel.locator('#port').fill(String(config.port));
  assert.equal(await panel.locator('#all-sites').isChecked(), true);
  assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get({ allSites: true })).allSites), true);
  mark('new and existing storage without allSites defaults to all sites');
  await panel.locator('#all-sites').uncheck();
  await panel.locator('#origins').fill(origin);
  await panel.locator('#save').click();
  await panel.waitForFunction(async () => (await chrome.runtime.sendMessage({ type: 'status' })).connectionState === '已连接');
  await panel.waitForFunction(() => document.getElementById('status').textContent === '已连接');
  if (!bridge.status().connected) throw new Error(`Bridge disconnected: ${JSON.stringify(await panel.evaluate(() => chrome.runtime.sendMessage({ type: 'status' })))}`);
  mark('real extension UI pairing and WebSocket handshake');
  client = new Client({ name: 'e2e-ai-client', version: '1' });
  await client.connect(new StdioClientTransport({ command: process.execPath, args: [join(ROOT, 'src', 'mcp.js')], env: { ...process.env, AIB_STATE_DIR: tempState } }));
  const tools = await client.listTools(); assert.equal(tools.tools.length, TOOLS.length); assert.equal(bridge.status().extensionVersion, '0.4.4'); mark('MCP tool discovery and extension version handshake');
  async function call(name, args = {}) {
    const result = await client.callTool({ name, arguments: args });
    if (result.isError) throw new Error(result.content[0].text);
    if (result.content[0].type === 'image') return result.content[0];
    return JSON.parse(result.content[0].text);
  }
  async function waitBridgeConnected() {
    let stable = 0;
    for (let i = 0; i < 80; i++) {
      const state = bridge.status();
      if (state.connected && !state.active && state.queued === 0) {
        stable++;
        if (stable >= 3) return;
      } else {
        stable = 0;
      }
      await new Promise(resolve => setTimeout(resolve, 100));
    }
    throw new Error(`Bridge did not reconnect: ${JSON.stringify(bridge.status())}`);
  }
  async function waitExtensionConnected() {
    let stable = 0;
    let lastState = null;
    for (let i = 0; i < 100; i++) {
      lastState = await panel.evaluate(() => chrome.runtime.sendMessage({ type: 'status' }));
      const bridgeState = bridge.status();
      if (lastState.connectionState === '已连接' && bridgeState.connected && !bridgeState.active && bridgeState.queued === 0) {
        stable++;
        if (stable >= 3) return;
      } else {
        stable = 0;
      }
      await new Promise(resolve => setTimeout(resolve, 100));
    }
    throw new Error(`Extension did not reconnect: ${JSON.stringify({ extension: lastState, bridge: bridge.status() })}`);
  }
  const opened = await call('browser_open', { url: `${origin}/fixture` }); const tabId = opened.tabId;
  const page = await context.waitForEvent('page', { timeout: 500 }).catch(() => context.pages().find(p => p.url().startsWith(origin)));
  await page.waitForLoadState('load');
  let read = await call('browser_read', { tabId });
  assert.ok(read.text.includes('本地浏览器验收'));
  for (const secret of ['PASSWORD_SECRET', 'HIDDEN_SECRET', 'PRIVATE_SECRET']) assert.ok(!JSON.stringify(read).includes(secret));
  mark('MCP opens and reads real page; hidden/password/private text excluded');
  const debug = await call('browser_debug', { tabId });
  assert.equal(debug.readyState, 'complete');
  assert.ok(debug.roleCounts.combobox >= 1);
  assert.equal(debug.fileInputs[0].accept, '.zip');
  mark('browser_debug reports page diagnostics without exposing private fields');
  const health = await call('browser_health', { tabId });
  assert.equal(health.connected, true);
  assert.equal(health.tab.allowed, true);
  assert.equal(health.tab.pageProbe.ok, true);
  const observed = await call('browser_observe', { tabId });
  assert.ok(observed.read.text.includes('本地浏览器验收'));
  assert.ok(observed.geometry.some(g => g.label === '消息草稿'));
  mark('browser_health and browser_observe provide layered diagnostics and geometry');
  const modes = await call('browser_bridge_modes', { tabId });
  assert.ok(modes.fallbackOrder.includes('coordinate-adapter'));
  const help = await call('browser_failure_help', { tabId, attemptedAction: 'browser_choose Task 108', error: 'Exact visible option not found' });
  assert.equal(help.category, 'picker');
  assert.equal(help.nextMode, 'picker-upload-bridge');
  mark('browser_bridge_modes and browser_failure_help guide fallback retries');
  read = await call('browser_read', { tabId });
  const aiStatus = await call('browser_ai_status');
  assert.equal(typeof aiStatus.apiPresent, 'boolean');
  assert.equal(typeof aiStatus.status, 'string');
  const judge = await call('browser_local_judge', { goal: 'Send a harmless local test message.', observation: JSON.stringify({ title: read.title, url: read.url, text: read.text.slice(0, 500) }), proposedAction: 'Click the local test page send button after filling a non-sensitive draft field.', riskLevel: 'low' });
  assert.ok(['allow', 'warn', 'block', 'unsure', 'unavailable'].includes(judge.verdict));
  assert.equal(judge.model, 'chrome-built-in-ai');
  assert.equal(typeof judge.schemaValid, 'boolean');
  assert.ok(Object.hasOwn(judge, 'parseWarning'));
  assert.equal(typeof judge.checks.needsHumanConfirm === 'boolean' || judge.checks.needsHumanConfirm === null, true);
  mark('optional Chrome built-in AI judge reports availability or advisory verdict without executing actions');
  const input = read.elements.find(e => e.label === '消息草稿');
  assert.equal(input.value, '');
  const button = read.elements.find(e => e.label === '发送到本地测试页');
  const combo = read.elements.find(e => e.label === '赛题选择');
  const chosen = await call('browser_choose', { tabId, ref: combo.ref, text: 'Task 108 topk_sigmoid' });
  assert.equal(chosen.chosen, 'Task 108 topk_sigmoid');
  read = await call('browser_read', { tabId });
  assert.equal(read.elements.find(e => e.label === '赛题选择').value, 'Task 108 topk_sigmoid');
  mark('custom combobox exact-text choice avoids keyboard and coordinate guessing');
  await page.locator('#task').click();
  read = await call('browser_read', { tabId });
  const openCombo = read.elements.find(e => e.label === '赛题选择');
  const openChosen = await call('browser_choose', { tabId, ref: openCombo.ref, text: 'Task 109 zero_experts_identity' });
  assert.equal(openChosen.chosen, 'Task 109 zero_experts_identity');
  read = await call('browser_read', { tabId });
  assert.equal(read.elements.find(e => e.label === '赛题选择').value, 'Task 109 zero_experts_identity');
  mark('browser_choose reuses an already-visible option without toggling the popup closed');
  const picked = await call('browser_pick', { tabId, label: '赛题选择', query: 'topk_sigmoid', chooseText: 'Task 108 topk_sigmoid' });
  assert.equal(picked.chosen, 'Task 108 topk_sigmoid');
  read = await call('browser_read', { tabId });
  assert.equal(read.elements.find(e => e.label === '赛题选择').value, 'Task 108 topk_sigmoid');
  mark('browser_pick finds a labeled custom picker and chooses exact text');
  const upload = read.elements.find(e => e.upload === true);
  assert.equal(upload.value, undefined);
  const selected = await call('browser_upload', { tabId, ref: upload.ref, filePath: uploadPath, sha256: uploadSha });
  assert.equal(selected.selected, true);
  assert.equal(selected.sha256, uploadSha);
  read = await call('browser_read', { tabId });
  assert.ok(read.text.includes(`已选择：fixture.zip:${uploadBytes.length}`));
  mark('root-confined SHA-bound upload selects a hidden file input without an OS dialog');
  const refreshedInput = read.elements.find(e => e.label === '消息草稿');
  const refreshedButton = read.elements.find(e => e.label === '发送到本地测试页');
  const fillVerified = await call('browser_fill_verified', { tabId, ref: refreshedInput.ref, text: '来自独立 AI 接口的消息', expect: { valueMatches: '来自独立 AI 接口的消息' } });
  assert.equal(fillVerified.status, 'success');
  const clickVerified = await call('browser_click_verified', { tabId, ref: refreshedButton.ref, expect: { textAppears: '本地回显：来自独立 AI 接口的消息' }, timeoutMs: 3000 });
  assert.equal(clickVerified.status, 'success');
  read = await call('browser_read', { tabId });
  assert.equal(read.elements.find(e => e.label === '消息草稿').value, '来自独立 AI 接口的消息');
  assert.equal(read.elements.find(e => e.label === '消息草稿').value, '来自独立 AI 接口的消息');
  assert.ok(read.text.includes('本地回显：来自独立 AI 接口的消息')); mark('MCP fills, clicks, and reads local chat-style response');
  const lease = await call('browser_claim_tab', { tabId, agent: 'e2e-agent', ttlMs: 30000 });
  assert.equal(lease.agent, 'e2e-agent');
  assert.equal((await call('browser_tab_lease', { tabId })).lease.agent, 'e2e-agent');
  assert.ok((await call('browser_read', { tabId })).text.includes('本地浏览器验收'));
  const waitingWithoutAgent = await call('browser_scroll', { tabId, deltaY: 10 });
  assert.equal(waitingWithoutAgent.status, 'waiting');
  assert.equal(waitingWithoutAgent.reason, 'tab_write_lease_conflict');
  assert.equal(waitingWithoutAgent.holder, 'e2e-agent');
  const waitingOtherAgent = await call('browser_scroll', { tabId, deltaY: 10, agent: 'other-agent' });
  assert.equal(waitingOtherAgent.status, 'waiting');
  assert.equal(waitingOtherAgent.holder, 'e2e-agent');
  await call('browser_scroll', { tabId, deltaY: 10, agent: 'e2e-agent' });
  await call('browser_release_tab', { tabId, agent: 'e2e-agent' });
  assert.equal((await call('browser_tab_lease', { tabId })).lease, null);
  mark('browser tab enforced lease returns waiting for unowned writes and allows owner writes');
  await assert.rejects(call('browser_click', { tabId, ref: button.ref }), /Stale/); mark('stale snapshot refs rejected');
  const replace = read.elements.find(e => e.label === '替换按钮');
  await page.locator('#replace').evaluate(el => el.textContent = '已改变的操作');
  await assert.rejects(call('browser_click', { tabId, ref: replace.ref }), /Stale/); mark('changed element semantics rejected');
  read = await call('browser_read', { tabId });
  const link = read.elements.find(e => e.label === '未授权链接');
  await assert.rejects(call('browser_click', { tabId, ref: link.ref }), /not allowed/);
  await assert.rejects(call('browser_open', { url: 'https://not-allowed.example/' }), /not allowed/); mark('unapproved origins blocked for open and direct links');
  const tabs = await call('browser_tabs'); assert.ok(tabs.some(t => t.id === tabId)); assert.ok(tabs.every(t => t.url.startsWith(origin))); mark('tab listing restricted to approved origins');
  // Independent HTTP client can use the same bridge without MCP or a model provider.
  const response = await fetch(`http://127.0.0.1:${config.port}/call`, { method: 'POST', headers: { Authorization: `Bearer ${config.agentToken}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ name: 'browser_scroll', arguments: { tabId, deltaY: 400 } }) });
  const scroll = await response.json(); assert.ok(scroll.result.scrollY > 0); mark('second HTTP client operates same extension');
  await call('browser_scroll', { tabId, deltaY: -400 });
  const screenshot = await call('browser_screenshot', { tabId }); assert.equal(screenshot.mimeType, 'image/png');
  const png = Buffer.from(screenshot.data, 'base64'); assert.equal(png.subarray(1, 4).toString(), 'PNG');
  writeFileSync(join(out, 'browser-result.png'), png); mark('real screenshot returned through MCP image content');
  await call('browser_navigate', { tabId, url: `${origin}/second` });
  await page.waitForURL(`${origin}/second`); await page.waitForLoadState('load');
  assert.equal((await call('browser_read', { tabId })).url, `${origin}/second`); mark('navigate and read verified');
  await page.evaluate(() => {
    const field = document.getElementById('draft');
    field.addEventListener('keydown', e => { if (e.key === 'Enter') document.getElementById('reply').textContent = `可信按键=${e.isTrusted}：${field.value}`; });
    const select = document.createElement('select'); select.setAttribute('aria-label', '选择测试'); select.innerHTML = '<option value="a">甲</option><option value="b">乙</option>'; document.body.prepend(select);
    document.getElementById('send').addEventListener('mouseover', e => { document.getElementById('reply').textContent = `悬停=${e.isTrusted}`; });
  });
  let currentRead = await call('browser_read', { tabId });
  await call('browser_fill', { tabId, ref: currentRead.elements.find(e => e.label === '消息草稿').ref, text: '键盘验证' });
  await call('browser_key', { tabId, ref: currentRead.elements.find(e => e.label === '消息草稿').ref, key: 'Enter' });
  assert.ok((await call('browser_read', { tabId })).text.includes('可信按键=true：键盘验证')); mark('CDP keyboard Enter is a trusted browser event');
  currentRead = await call('browser_read', { tabId });
  assert.deepEqual(currentRead.elements.find(e => e.label === '选择测试').options.map(o => o.value), ['a', 'b']);
  await call('browser_select', { tabId, ref: currentRead.elements.find(e => e.label === '选择测试').ref, value: 'b' });
  assert.deepEqual(currentRead.elements.find(e => e.label === '选择测试').options.map(o => o.value), ['a', 'b']);
  assert.equal(await page.locator('select').inputValue(), 'b');
  await call('browser_hover', { tabId, ref: currentRead.elements.find(e => e.label === '发送到本地测试页').ref });
  assert.ok((await call('browser_read', { tabId })).text.includes('悬停=true')); mark('native select and trusted hover work');
  await page.evaluate(() => setTimeout(() => { document.getElementById('reply').textContent = '异步结果已出现'; }, 500));
  assert.equal((await call('browser_wait', { tabId, text: '异步结果已出现', timeoutMs: 3000 })).matched, true); mark('DOM-event wait observes delayed page changes');
  const inputBox = await page.locator('#draft').boundingBox();
  const viewport = (await call('browser_read', { tabId })).viewport;
  await call('browser_action', { tabId, action: 'Tap', expectedUrl: `${origin}/second`, x: (inputBox.x + inputBox.width / 2) / viewport.width * 1000, y: (inputBox.y + inputBox.height / 2) / viewport.height * 1000 });
  await call('browser_action', { tabId, action: 'Type', expectedUrl: `${origin}/second`, text: '归一化动作验证' });
  await call('browser_action', { tabId, action: 'Key', expectedUrl: `${origin}/second`, key: 'Enter' });
  assert.ok((await call('browser_read', { tabId })).text.includes('可信按键=true：归一化动作验证'));
  await assert.rejects(call('browser_action', { tabId, action: 'Tap', expectedUrl: `${origin}/old`, x: 20, y: 20 }), /stale/); mark('Open-AutoGLM coordinate Type and Key adapter with stale URL rejection');
  const assistant = await context.newPage(); await assistant.goto(`chrome-extension://${extensionId}/assistant.html`);
  await assistant.locator('#target').selectOption(String(tabId)); await assistant.locator('#task').fill('本地模拟验收：填写测试消息并按 Enter。');
  await assistant.locator('#run').click();
  await assistant.waitForFunction(() => document.getElementById('task-status').textContent.includes('模型报告完成'));
  assert.ok((await call('browser_read', { tabId })).text.includes('可信按键=true：来自模拟模型的任务'));
  await assistant.screenshot({ path: join(out, 'assistant-task.png'), fullPage: true }); mark('assistant UI to simulated model to real Chrome actions completes bounded task');
  mockMode = 'slow'; const previousRequests = modelRequests;
  await assistant.waitForFunction(() => !document.getElementById('run').disabled);
  await assistant.locator('#run').click();
  for (let i = 0; i < 100 && modelRequests === previousRequests; i++) await new Promise(resolve => setTimeout(resolve, 50));
  assert.ok(modelRequests > previousRequests);
  const taskWaiting = await call('browser_read', { tabId });
  assert.equal(taskWaiting.status, 'waiting');
  assert.equal(taskWaiting.reason, 'global_agent_task_lease');
  mark('agent task lease returns waiting for other clients without ending their tasks');
  await assistant.locator('#cancel').click();
  await assistant.waitForFunction(() => document.getElementById('task-status').textContent === '已停止');
  assert.ok((await call('browser_read', { tabId })).text.includes('来自模拟模型的任务')); mark('cancel aborts model request and releases task lease without extra actions');
  await assistant.close();
  await panel.locator('#all-sites').check();
  await panel.locator('#save').click();
  await waitExtensionConnected();
  assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('allSites')).allSites), true);
  assert.deepEqual(await worker.evaluate(async () => (await chrome.storage.local.get('allowedOrigins')).allowedOrigins), [origin]);
  const second = await call('browser_open', { url: `${otherOrigin}/unlisted` });
  let secondPage;
  for (let attempt = 0; attempt < 20; attempt++) {
    secondPage = context.pages().find(p => p.url().startsWith(otherOrigin));
    if (secondPage) break;
    await new Promise(resolve => setTimeout(resolve, 50));
  }
  assert.ok(secondPage); await secondPage.waitForLoadState('load');
  const secondRead = await call('browser_read', { tabId: second.tabId });
  await call('browser_fill', { tabId: second.tabId, ref: secondRead.elements.find(e => e.label === '消息草稿').ref, text: '所有网站模式' });
  await call('browser_click', { tabId: second.tabId, ref: secondRead.elements.find(e => e.label === '发送到本地测试页').ref });
  assert.ok((await call('browser_read', { tabId: second.tabId })).text.includes('本地回显：所有网站模式'));
  assert.ok((await call('browser_tabs')).some(t => t.id === second.tabId));
  mark('all-sites mode opens reads fills clicks and lists an origin absent from whitelist');
  await page.locator('a').evaluate((el, target) => { el.href = target; }, `${otherOrigin}/cross-site-link`);
  const crossRead = await call('browser_read', { tabId });
  await call('browser_click', { tabId, ref: crossRead.elements.find(e => e.tag === 'a').ref });
  await page.waitForURL(`${otherOrigin}/cross-site-link`); await page.waitForLoadState('load');
  assert.equal((await call('browser_read', { tabId })).url, `${otherOrigin}/cross-site-link`);
  await call('browser_navigate', { tabId, url: `${origin}/back` });
  await page.waitForURL(`${origin}/back`); await page.waitForLoadState('load');
  await assert.rejects(call('browser_open', { url: 'chrome://settings' }), /HTTP/);
  await assert.rejects(call('browser_open', { url: 'file:///C:/example.txt' }), /HTTP/);
  mark('cross-origin link and navigation work; internal and local-file URLs remain excluded');
  await panel.locator('#all-sites').uncheck(); await panel.locator('#save').click();
  await waitExtensionConnected();
  await assert.rejects(call('browser_read', { tabId: second.tabId }), /not allowed/);
  assert.ok(!(await call('browser_tabs')).some(t => t.id === second.tabId));
  mark('switching back to saved whitelist immediately limits reads and tab listing');
  await panel.locator('#all-sites').check(); await panel.locator('#save').click();
  await waitExtensionConnected();
  await call('browser_close', { tabId: second.tabId });
  await panel.locator('#pause').click();
  await panel.waitForFunction(async () => !(await chrome.storage.local.get('enabled')).enabled);
  await assert.rejects(call('browser_tabs'), /not connected|paused|lost/); mark('user pause stops subsequent commands');
  await panel.locator('#reconnect').click();
  await waitExtensionConnected();
  await call('browser_close', { tabId }); assert.ok(!(await call('browser_tabs')).some(t => t.id === tabId)); mark('explicit reconnect and close verified');
  await panel.locator('#refresh').click(); await panel.screenshot({ path: join(out, 'extension-panel.png'), fullPage: true });
  writeFileSync(join(out, 'e2e-report.json'), JSON.stringify({ date: new Date().toISOString(), browser: context.browser()?.version() ?? 'persistent Chromium', extensionId, checks, status: 'passed', fixtureOnly: true, normalChromeProfileConnected: false }, null, 2));
  console.log(`All ${checks.length} browser checks passed. Artifacts: output/playwright/`);
} catch (error) {
  writeFileSync(join(out, 'e2e-failure.json'), JSON.stringify({ date: new Date().toISOString(), checks, error: error.stack }, null, 2));
  throw error;
} finally {
  await client?.close(); await context?.close(); await bridge.close(); await new Promise(resolve => fixture.close(resolve));
  await new Promise(resolve => otherFixture.close(resolve));
  mockModel.closeAllConnections(); await new Promise(resolve => mockModel.close(resolve));
}
